name: "Tag & create GitHub release"

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Get lib version and set environment variable
      id: get-version
      run: |
        VERSION=$(grep 'VERSION' src/Constants.php |  grep -oE '[0-9]+\.[0-9]+\.([0-9]+|[0-9]+-[a-z]+)')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Create and publish tag
      run: |
        git tag $VERSION
        if [[ $? -ne 0 ]]; then
          echo "Tag $VERSION already exists. Skipping tag creation."
          exit 1
        fi
        git push origin $VERSION

  create-release:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: Github Release
      uses: taiki-e/create-gh-release-action@eba8ea96c86cca8a37f1b56e94b4d13301fba651 # v1.11.0
      with:
        token: ${{ secrets.GITHUB_TOKEN}}
        ref: refs/tags/${{ needs.create-tag.outputs.version }}
        changelog: "CHANGELOG.md"
